# Archivo obsoleto - ahora usando Railpack en railway.toml
# Mantenido para referencia

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.build]
cmds = [
  "pnpm install --frozen-lockfile --production=false",
  "pnpm exec prisma generate",
  "pnpm run build",
  "pnpm prune --prod"
]

[start]
cmd = "pnpm run start:prod"