[build]
builder = "nixpacks"
buildCommand = "pnpm install --frozen-lockfile && pnpm run build"

[deploy]
startCommand = "pnpm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
NODE_ENV = "production"