[build]
builder = "railpack"
buildCommand = "pnpm install --frozen-lockfile && pnpm run db:generate && pnpm run build"
watchPaths = ["apps/telegram-bot/**", "packages/**"]

[railpack]
nodeVersion = "20"
packageManager = "pnpm"

[deploy]
startCommand = "cd packages/database && npx prisma migrate deploy && cd ../.. && node apps/telegram-bot/dist/index.js"
restartPolicyType = "always"

[env]
NODE_ENV = "production"
PORT = "3000"
LOG_LEVEL = "info"