[build]
builder = "railpack"
watchPaths = ["apps/telegram-bot/**", "packages/**"]

[deploy]
startCommand = "node dist/apps/telegram-bot/src/index.js"
restartPolicyType = "always"

[env]
NODE_ENV = "production"
PORT = "3000"
LOG_LEVEL = "info"