[build]
builder = "railpack"
buildCommand = "pnpm install --frozen-lockfile && pnpm run db:generate && pnpm run build"
watchPaths = ["apps/telegram-bot/**", "packages/**"]

[deploy]
startCommand = "node dist/apps/telegram-bot/src/index.js"
restartPolicyType = "always"

[env]
NODE_ENV = "production"
PORT = "3000"
LOG_LEVEL = "info"